spring:
  application:
    name: gateway
  docker:
    compose:
      enabled: true
      file: ./docker-compose.yml
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: lb://auth
          predicates:
            - Path=/bizznetbb/auth/**
        - id: other_service
          uri: lb://OTHER-SERVICE
          predicates:
            - Path=/other/**
          filters:
            - JwtAuthFilter
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

# Eureka - Registry Service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://registry-service:8761/eureka/}

server:
  port: 8080
  servlet:
        context-path: /bizznetbb-api/
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG